version: '3.8'

services:
  redis:
    image: redis
    container_name: smite-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  postgres:
    image: postgres
    container_name: smite-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smite
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  redis-data:
  postgres-data:
