version: '3.8'

services:
  redis:
    image: redis
    container_name: smite-redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  mysql:
    image: mysql
    container_name: smite-mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=smite
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  redis-data:
  mysql-data:
